#if UNITY_EDITOR
namespace UtilsModule.Other
{
    using System.IO;
    using System.Linq;
    using System.Text.RegularExpressions;
    using UnityEditor;
    using UnityEngine;

    public static class EnumGenerator
    {
        /// <summary>
        /// Генерация enum-файла по списку имён.
        /// </summary>
        /// <param name="names">Список имён для enum.</param>
        /// <param name="namespaceName">
        /// Имя namespace для enum. По умолчанию "Generated", чтобы не менять существующее поведение.
        /// </param>
        /// <param name="enumName">
        /// Имя enum.
        /// </param>
        public static void GenerateEnum(
            string[] names,
            string enumName,
            string path,
            string namespaceName = "Generated")
        {
            if (names == null || names.Length == 0)
            {
                EditorUtility.DisplayDialog("Error", "No names provided for enum generation.", "OK");
                return;
            }

            // Убедимся, что путь абсолютный
            string fullPath = Path.GetFullPath(path + "/" + enumName + ".cs");
            string directory = Path.GetDirectoryName(fullPath);

            // Проверка и создание директории
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // Удаление существующего файла, если есть
            if (File.Exists(fullPath))
            {
                File.Delete(fullPath);
            }

            // Формируем enum
            var enumEntries = names
                .Select(SanitizeEnumName)
                .Select(name => $"    {name}")
                .ToArray();

            string enumContent = $@"// Auto-generated by EnumGenerator
// Do not modify manually

namespace {namespaceName}
{{
    public enum {enumName}
    {{
    {string.Join(",\n \t", enumEntries)}
    }}
}}
";

            // Сохраняем
            File.WriteAllText(fullPath, enumContent);

            // Обновляем AssetDatabase
            AssetDatabase.Refresh();

            Debug.Log($"{enumName} enum generated at: {path}");
            EditorUtility.RevealInFinder(directory);
        }

        // Приводит имя к валидному имени enum (если содержит недопустимые символы)
        private static string SanitizeEnumName(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "InvalidName";

            // Заменяем пробелы и дефисы на подчеркивания
            string sanitized = name
                .Replace(' ', '_')
                .Replace('-', '_')
                .Replace('.', '_');

            // Если начинается с цифры — добавляем префикс
            if (!string.IsNullOrEmpty(sanitized) && char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }

            // Убираем всё, кроме букв, цифр и подчеркиваний
            sanitized = Regex.Replace(sanitized, @"[^a-zA-Z0-9_]", "");

            return string.IsNullOrEmpty(sanitized)
                ? "InvalidName"
                : sanitized;
        }
    }
}
#endif